--------------------------------------------------------
--  파일이 생성됨 - 월요일-11월-07-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table GOODS_CATEGORY
--------------------------------------------------------

  CREATE TABLE "MINI"."GOODS_CATEGORY" 
   (	"CATENAME" VARCHAR2(20 BYTE), 
	"CATECODE" VARCHAR2(30 BYTE), 
	"CATECODEREF" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBL_GOODS
--------------------------------------------------------

  CREATE TABLE "MINI"."TBL_GOODS" 
   (	"GDSNUM" NUMBER, 
	"GDSNAME" VARCHAR2(50 BYTE), 
	"CATECODE" VARCHAR2(30 BYTE), 
	"GDSPRICE" NUMBER, 
	"GDSSTOCK" NUMBER, 
	"GDSDES" VARCHAR2(500 BYTE), 
	"GDSIMG" VARCHAR2(200 BYTE), 
	"GDSDATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBL_MEMBER
--------------------------------------------------------

  CREATE TABLE "MINI"."TBL_MEMBER" 
   (	"USERID" VARCHAR2(50 BYTE), 
	"USERPASS" VARCHAR2(100 BYTE), 
	"USERNAME" VARCHAR2(30 BYTE), 
	"USERPHON" VARCHAR2(20 BYTE), 
	"USERADDR1" VARCHAR2(20 BYTE), 
	"USERADDR2" VARCHAR2(50 BYTE), 
	"USERADDR3" VARCHAR2(50 BYTE), 
	"REGIDATE" DATE DEFAULT sysdate, 
	"VERIFY" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into MINI.GOODS_CATEGORY
SET DEFINE OFF;
Insert into MINI.GOODS_CATEGORY (CATENAME,CATECODE,CATECODEREF) values ('무기','100',null);
Insert into MINI.GOODS_CATEGORY (CATENAME,CATECODE,CATECODEREF) values ('돌격소총','101','100');
Insert into MINI.GOODS_CATEGORY (CATENAME,CATECODE,CATECODEREF) values ('기관단총','102','100');
Insert into MINI.GOODS_CATEGORY (CATENAME,CATECODE,CATECODEREF) values ('경기관총','103','100');
Insert into MINI.GOODS_CATEGORY (CATENAME,CATECODE,CATECODEREF) values ('산탄총','104','100');
Insert into MINI.GOODS_CATEGORY (CATENAME,CATECODE,CATECODEREF) values ('지정사수소총','105','100');
Insert into MINI.GOODS_CATEGORY (CATENAME,CATECODE,CATECODEREF) values ('저격소총','106','100');
Insert into MINI.GOODS_CATEGORY (CATENAME,CATECODE,CATECODEREF) values ('기타','107','100');
Insert into MINI.GOODS_CATEGORY (CATENAME,CATECODE,CATECODEREF) values ('탄','200',null);
Insert into MINI.GOODS_CATEGORY (CATENAME,CATECODE,CATECODEREF) values ('방어구','300',null);
Insert into MINI.GOODS_CATEGORY (CATENAME,CATECODE,CATECODEREF) values ('회복제','400',null);
REM INSERTING into MINI.TBL_GOODS
SET DEFINE OFF;
REM INSERTING into MINI.TBL_MEMBER
SET DEFINE OFF;
Insert into MINI.TBL_MEMBER (USERID,USERPASS,USERNAME,USERPHON,USERADDR1,USERADDR2,USERADDR3,REGIDATE,VERIFY) values ('아이디','비밀번호','닉네임','전화번호',null,null,null,to_date('22/11/06','RR/MM/DD'),0);
Insert into MINI.TBL_MEMBER (USERID,USERPASS,USERNAME,USERPHON,USERADDR1,USERADDR2,USERADDR3,REGIDATE,VERIFY) values ('aaa@aaa.com','$2a$10$bbriz.BQCQe4u9KILoUUCOoMsmd8iM/70.12DfwA7K2/Bposs9SPS','admin','010-1111-2222',null,null,null,to_date('22/11/06','RR/MM/DD'),9);
Insert into MINI.TBL_MEMBER (USERID,USERPASS,USERNAME,USERPHON,USERADDR1,USERADDR2,USERADDR3,REGIDATE,VERIFY) values ('aodnsrhf@naver.com','$2a$10$qQnB7qcZknE8vg4ax3v2w.fv99I0e1RDhrzcnKBATHJjsVMFm44j6','9mori','010-2222-3333',null,null,null,to_date('22/11/06','RR/MM/DD'),9);
Insert into MINI.TBL_MEMBER (USERID,USERPASS,USERNAME,USERPHON,USERADDR1,USERADDR2,USERADDR3,REGIDATE,VERIFY) values ('bbb@bbb.com','1234','aaa','010-3333-4444',null,null,null,to_date('22/11/06','RR/MM/DD'),0);
--------------------------------------------------------
--  DDL for Index SYS_C007009
--------------------------------------------------------

  CREATE UNIQUE INDEX "MINI"."SYS_C007009" ON "MINI"."GOODS_CATEGORY" ("CATECODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007006
--------------------------------------------------------

  CREATE UNIQUE INDEX "MINI"."SYS_C007006" ON "MINI"."TBL_GOODS" ("GDSNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007001
--------------------------------------------------------

  CREATE UNIQUE INDEX "MINI"."SYS_C007001" ON "MINI"."TBL_MEMBER" ("USERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table GOODS_CATEGORY
--------------------------------------------------------

  ALTER TABLE "MINI"."GOODS_CATEGORY" ADD PRIMARY KEY ("CATECODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MINI"."GOODS_CATEGORY" MODIFY ("CATECODE" NOT NULL ENABLE);
  ALTER TABLE "MINI"."GOODS_CATEGORY" MODIFY ("CATENAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_GOODS
--------------------------------------------------------

  ALTER TABLE "MINI"."TBL_GOODS" ADD PRIMARY KEY ("GDSNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MINI"."TBL_GOODS" MODIFY ("GDSPRICE" NOT NULL ENABLE);
  ALTER TABLE "MINI"."TBL_GOODS" MODIFY ("CATECODE" NOT NULL ENABLE);
  ALTER TABLE "MINI"."TBL_GOODS" MODIFY ("GDSNAME" NOT NULL ENABLE);
  ALTER TABLE "MINI"."TBL_GOODS" MODIFY ("GDSNUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_MEMBER
--------------------------------------------------------

  ALTER TABLE "MINI"."TBL_MEMBER" ADD PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MINI"."TBL_MEMBER" MODIFY ("USERPHON" NOT NULL ENABLE);
  ALTER TABLE "MINI"."TBL_MEMBER" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "MINI"."TBL_MEMBER" MODIFY ("USERPASS" NOT NULL ENABLE);
  ALTER TABLE "MINI"."TBL_MEMBER" MODIFY ("USERID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table GOODS_CATEGORY
--------------------------------------------------------

  ALTER TABLE "MINI"."GOODS_CATEGORY" ADD FOREIGN KEY ("CATECODEREF")
	  REFERENCES "MINI"."GOODS_CATEGORY" ("CATECODE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_GOODS
--------------------------------------------------------

  ALTER TABLE "MINI"."TBL_GOODS" ADD CONSTRAINT "FK_GOODS_CATEGORY" FOREIGN KEY ("CATECODE")
	  REFERENCES "MINI"."GOODS_CATEGORY" ("CATECODE") ENABLE;
